name: CI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.x'

      - name: Get version
        id: version
        run: echo "version-without-v=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
     
      - name: Publish Database Abstraction Nuget Package
        id: publish_nuget_database_abstraction
        uses: cardboards-box/publish-nuget@v1.0.0
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Database.Abstraction/CardboardBox.Database.Abstraction.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.version.outputs.version-without-v }}
     
      - name: Publish Database Nuget Package
        id: publish_nuget_database
        uses: cardboards-box/publish-nuget@v1.0.0
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Database/CardboardBox.Database.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.version.outputs.version-without-v }}
          
      - name: Publish Database Postgres Nuget Package
        id: publish_nuget_database_postgres
        uses: cardboards-box/publish-nuget@v1.0.0
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Database.Postgres/CardboardBox.Database.Postgres.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.version.outputs.version-without-v }}
          
      - name: Publish Database Sqlite Nuget Package
        id: publish_nuget_database_sqlite
        uses: cardboards-box/publish-nuget@v1.0.0
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Database.Sqlite/CardboardBox.Database.Sqlite.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.version.outputs.version-without-v }}
          
      - name: Publish Database Postgres Standard Nuget Package
        id: publish_nuget_database_postgres_standard
        uses: cardboards-box/publish-nuget@v1.0.0
        with:
          PROJECT_FILE_PATH: src/CardboardBox.Database.Postgres.Standard/CardboardBox.Database.Postgres.Standard.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.version.outputs.version-without-v }}